version: '3'

services:
  mongo:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    env_file:
      - .env
    volumes:
      - ./dbdata:/data/db
    ports:
      - 27017:27017
  
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
  
  nginx:
    image: creport-frontend
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/:/etc/nginx/conf.d/
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    env_file:
      - .env
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  apiservice:
    image: creport-api
    container_name: api
    ports:
      - 3000:3000
    restart: always
    env_file:
      - .env
    command: "/bin/sh -c 'cd /app/api ; node dist/main'"
